name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build & push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to registry
      with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
              
    - uses: actions/checkout@v3        
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=0 docker build . --file Dockerfile --tag app-image:$(date +%s)
      
    - uses: actions/checkout@v3      
    - name: Push image  
      run: docker push ghcr.io/korneevev/app-image:latest
     
